### ISSUE TITLE
3d transform function support

### ISSUE THREAD

**Issue by jeremiahmmv2** [jeremyckahn/rekapi#38]
I can only seem to get rotate3d() to work if it's included in the `transform:` keyframe property. The only drawback to this is that easing is applied to the transform as a whole (including the `translate` position). Is there any way of using a separate `rotate3d:` property in a keyframe?

I thought a workaround might be to use matrix3d() to keep the vertices in the correct position when using timing functions such as `easeInCirc`, but that doesn't seem to be supported. I see that matrix() is supported, but rotation seems to break it.

There's a [plugin](https://github.com/mvayngrib/TweenJSPlugins/blob/master/Matrix3DDemo.html) available for TweenJS that uses matrix3d() with timing functions that works as expected. I may need to support both Rekapi and TweenJS in my project if such a feature is unfeasible in Rekapi. 

Perhaps I'm just using Rekapi wrong. Please let me know your thoughts or suggestions.

**Comment by jeremyckahn** [comment]
Hi @jeremiahmmv2, thanks for bringing this up.  Transform functions that take multiple parameters are not currently supported when using [the decoupled form of the API](http://rekapi.com/dist/doc/classes/Rekapi.DOMRenderer.html#method_setActorTransformOrder).

However, since Rekapi is built on top of [Shifty](http://jeremyckahn.github.io/shifty/) and its [token parsing engine](http://jeremyckahn.github.io/shifty/dist/doc/modules/Tweenable.token.html), you can have complex strings with multiple numbers that each have different easing functions.  So, something like this should work (I haven't run this myself yet):

````javascript
var rekapi = new Rekapi(document.body);
var actor = rekapi.addActor(document.getElementById('actor'));

actor
  .keyframe(0, { 
    transform: 'rotate3d(0, 0, 0, 0deg)'
  })
  .keyframe(1000, { 
    transform: 'rotate3d(5, 10, 15, 180deg)'
  }, {
    transform: 'linear easeInQuad easeInCubic easeInQuart'
  });
````

Alternatively you could stick with Rekapi's decoupled transform API and used the [longhand forms](http://stackoverflow.com/questions/15207351/rotate3d-shorthand) of the rotation transform functions.

Would any of these approaches work for you?

**Comment by jeremiahmmv2** [comment]
Great. The first option works. I wasn't aware that I could simply put multiple space-delimited timing functions.

Just curious, is there any plan to add support for matrix3d() in Shifty's token parsing engine?

**Comment by jeremyckahn** [comment]
Glad it'll work for you!  What kind of support would you be looking for with regards to Shifty/Rekapi and matrix3d?
