### ISSUE TITLE
Changing the transform-origin per keyframe

### ISSUE THREAD

**Issue by jeremiahmmv2** [jeremyckahn/rekapi#42]
In my project I'm going to allow use of CSS keyframe animations generated with Rekapi. In the pure Rekapi implementation, I used `function` keyframe properties to change the `transform-origin` when needed. However, when using the CSS animation option, there doesn't seem to be a way to change the `transform-origin` at a given keyframe or animation. 

Example: An element that rotates and scales into view (`center center`), then uses a hinge-type animation to fall out of view (`left top`).

This seems like somewhat of an edge case, but the ability to change the `transform-origin` at any given time would go a long way in chaining animations together.

In the meantime, I'll implement an option to edit the animation CSS for advanced users. Or I could use regex to replace the function keyframe property in the generated CSS. However, both of these options would mean completely decoupling my front-end implementation from Rekapi in favor of a `setTimeout` implementation that simply adds the actor class at the appropriate time.

**Comment by jeremyckahn** [comment]
Hi @jeremiahmmv2, I think you should be able to achieve the animation you want by not passing `isCentered` to `DOMRenderer#toString`, and instead treating `transform-origin` as a regular animation property with `Rekapi#keyframe`.  Would that achieve the effect you're going for?

**Comment by jeremiahmmv2** [comment]
Ohhh, I think the problem occurs when I try to use non-percentage positions such as `center center` instead of `50% 50%`. Percentages seem to work as expected.

**Comment by jeremyckahn** [comment]
Great!  Yes, Rekapi can animate any string, so long as it contains at least one number.  Sounds like you're set, so I'll close this out.

Out of curiosity, what are you building?

**Comment by jeremiahmmv2** [comment]
I'm building a slider for various content management systems. I'm currently refactoring the admin slideshow/animation creator as an Ember 2 application. So I'm taking the time to make the animations more performant. 

Each layer (image, video, text, html) can have a starting and ending animation.

I have an admin component that's similar to Stylie to create custom animations. I would have used Stylie but I needed more options such as absolute positioning (`left`, `top`), `transform-origin` for each keyframe and skew support.

Originally I had planned to directly use Rekapi even in the public-facing slideshows. The main reason being pause-able animations. However, I feel most users would probably forego that feature for better performing animations. I'll likely keep that as an option, but have CSS as the default.

My new plan is to generate the animation CSS for each layer in admin. For the front end, I'll either A) programmatically store the animation CSS in a .css file for each slideshow or B) store the CSS within the slideshow's JSON object and create the `<style>` element dynamically. Maybe A with a B fallback in case of a non-writable directory.

The trick will be making these options appear super easy to understand and change for novice users. I guess that's always true with UX.

Hopefully some of this will help the direction of Rekapi 2.0/Stylie.

**Comment by jeremyckahn** [comment]
Wow, what you're building sounds really cool!  I'd love to see it when it's finished, if it's something that will be publicly accessible.

You mentioned storing CSS as data and dynamically injecting it into the page — I've done this in projects and it does work.  It seems that not a lot of people take this approach, but in my experience it scales and works quite well.

Rekapi 2.0 is going to be very different from 1.x.  It's a total rewrite, and I'm tweaking some of the core philosophies of the project as well as a lot of the APIs.  I'm still figuring out what exactly it needs to be, but generally I'm envisioning Rekapi as a more robust timeline data model than it is currently.  My main goal with the new design is to make Rekapi more suitable for reactive UIs, as well as making state changes more manageable.  Since 2.0 will be incompatible with 1.x, I will be maintaining 1.x in its own branch on an ongoing basis.

It's going to be a while before 2.0 exists in any meaningful form, as I don't have as much time to work on OSS as I used to.  Thanks for your input!

**Comment by jeremyckahn** [comment]
Also, in case your application needs some sort of graphical timeline controls, you might find [rekapi-timeline](https://github.com/jeremyckahn/rekapi-timeline) useful.
