### ISSUE TITLE
How does Rekapi work?

### ISSUE THREAD

**Issue by evbo** [jeremyckahn/rekapi#67]
Hi, I am interested in high performance CSS animation, so am curious when you write that Rekapi doesn't do any rendering. When I look in your renderers package, I think it's simply converting everything into CSS, is that true?

So does Rekapi generate CSS at runtime when the page is first loaded? Would the benefit of CSS hardware acceleration get applied by the browser? Or is there runtime overhead from the javascript code that might ultimately bottleneck any performance gains of CSS hardware acceleration?

**Comment by jeremyckahn** [comment]
Hi @evbo, thanks for your interest in Rekapi and how it works! When I say that Rekapi doesn't do any rendering, I mean that it's not tied to a specific way of rendering an animation. Rekapi is focused on maintaining a keyframe data model. On every tick of an animation, it hands its state off to some user-defined/chosen rendering mechanism (such as the standard [DOM](https://github.com/jeremyckahn/rekapi/blob/master/src/renderers/dom.js) or [Canvas](https://github.com/jeremyckahn/rekapi/blob/master/src/renderers/canvas.js) renderer implementations).

There's a deviation from the "render every tick" pattern for CSS `@keyframe` animations ([`rekapi.DOMRenderer#getCss`](https://jeremyckahn.github.io/rekapi/doc/rekapi.DOMRenderer.html#getCss)). This method performs a one-time upfront operation of converting Rekapi's internal state to a big CSS string. It's then up to the user of Rekapi to do something with that string. As a convenience, there is [`rekapi.DOMRenderer#play`](https://jeremyckahn.github.io/rekapi/doc/rekapi.DOMRenderer.html#play), which essentially calls `getCss`, and then [injects the produced CSS string into the DOM](https://github.com/jeremyckahn/rekapi/blob/06e1ee55827ec6692861ac530addd5aafddae827/src/renderers/dom.js#L152-L166). From there the browser naturally runs the animation as a [CSS `@keyframe` animation](https://developer.mozilla.org/en-US/docs/Web/CSS/@keyframes).

> Would the benefit of CSS hardware acceleration get applied by the browser?

Yep! That's the primary benefit of Rekapi's `DOMRenderer`. It hands off the animation to the browser's hardware-accelerated CSS engine and leaves the JS thread free for other work.

> Or is there runtime overhead from the javascript code that might ultimately bottleneck any performance gains of CSS hardware acceleration?

Potentially, yes. Compiling the CSS string is a somewhat expensive operation, so you'd want to be careful with how often you do it. It's a good fit for scenarios where the composition of an animation is known upfront and is not likely to change too often. You shouldn't be afraid to update/recompute the animation, just be judicious with it.

Does this answer your questions? It's been a few years since I've actively worked on Rekapi, so my recollection of some of the internals is admittedly a bit fuzzy. 😅

**Comment by evbo** [comment]
@jeremyckahn thank you! I get the impression that if I were to cache all my css animations upfront (and if they didn't change like you say) then I'd get good runtime performance.

This is a great library, I'm sorry you're not getting more chances to keep up with it. I'm happy to close this issue but hearing that Rekapi might not be very actively maintained did just spur a follow up question I'd appreciate your thoughts on:

I'm new to CSS keyframe development (for years I've seen it as just a novelty) but it's striking me as incredibly powerful yet unwieldy and desperately in need of something like Rekapi in order to be manageable in large projects. But am I correct in my assessment that industry by in large seems focused on CSS as it relates to UI components, like the popular [styled-components](https://github.com/styled-components/styled-components) or [Linaria](https://github.com/callstack/linaria)? Even popular game engines like [Phaser](https://github.com/photonstorm/phaser) seem to rely heavily on Canvas instead of SVG/CSS. Is there no other tool focused on keyframes quite like Rekapi? How are CSS keyframe animators doing this without Rekapi? Just text and a web browser?!

Thanks for any clarification, references, or observations into keyframe development workflows you may be aware of. I see myself likely using Rekapi, but I'm mostly just shocked and amazed how else keyframes are getting made!

**Comment by jeremyckahn** [comment]
I'm glad you like Rekapi! I wouldn't say that the project is unmaintained, it's just not being actively developed these days. If a bug or issue is reported, I'd get it addressed. That said, the project is pretty stable and I don't have plans to add features right now.

> But am I correct in my assessment that industry by in large seems focused on CSS as it relates to UI components, like the popular styled-components or Linaria?

It seems that way, yeah. CSS keyframes are very powerful, but the syntax is a little clunk as you pointed out. Libraries like Rekapi were developed to try and tame it to varying degrees of success, but they never really caught on. That said, CSS keyframes are a stable W3C standard, so they're as viable an animation option as anything if the use case warrants it.

>  Is there no other tool focused on keyframes quite like Rekapi? How are CSS keyframe animators doing this without Rekapi? Just text and a web browser?!

There are a variety of UI tools out there to make CSS animations easier to work with, such as https://keyframes.app/  and http://cssanimate.com/. There's also [Stylie](https://jeremyckahn.github.io/stylie/) and [Mantra](https://jeremyckahn.github.io/mantra/), open source web apps that are each built on top of Rekapi. They let you experiment with an animation and export it as CSS keyframes. I think the more commercial options cover web animation more broadly, but I haven't used any of them personally.

> Thanks for any clarification, references, or observations into keyframe development workflows you may be aware of. I see myself likely using Rekapi, but I'm mostly just shocked and amazed how else keyframes are getting made!

You're welcome! I'm happy to help. It's nice to find someone else who's actually interested in this stuff. 🙂 I hope you find Rekapi useful! It's still fit for use, but if you run into any roadblocks or have any questions, feel free to file a bug here or [start a discussion thread](https://github.com/jeremyckahn/rekapi/discussions)!
